site :opscode

cookbook "project_workspace", path: "../../cookbooks/project_workspace"
cookbook "nodejs_workspace", path: "../../cookbooks/nodejs_workspace"
cookbook "vslinko", github: "vslinko/cookbook-vslinko"

# see https://github.com/opscode-cookbooks/apt/pull/53
cookbook "apt", github: "opscode-cookbooks/apt"
