Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "mongodb"
    chef.add_recipe "nodejs_workspace"

    chef.json = {
      :nodejs_workspace => {
        :project => {
          :name => "pegas-crm"
        }
      }
    }
  end
end
