site :opscode

cookbook "project_workspace", path: "../../cookbooks/project_workspace"
cookbook "polartour_workspace", path: "../../cookbooks/polartour_workspace"
cookbook "vslinko", path: "../cookbook-vslinko"

# see https://github.com/opscode-cookbooks/apt/pull/53
cookbook "apt", github: "opscode-cookbooks/apt"
